const initalData = {
  columns: {
    "column-0": {
      id: "column-0",
      icon: "👀",
      title: "Work",
      items: [],
      isCompact: false,
    },
    "column-1": {
      id: "column-1",
      icon: "🦴",
      title: "Study",
      items: [],
      isCompact: true,
    },
    "column-2": {
      id: "column-2",
      icon: "🐶",
      title: "Personal",
      items: [],
      isCompact: false,
    },
  },
  columnOrder: ["column-0", "column-1", "column-2"],
  theme: "light",
};

export const sampleTabs = [
  { id: 110, title: "Modern React with Redux", url: "http://google.ca", favIconUrl: "https://www.udemy.com/staticx/udemy/images/v6/favicon-32x32.png" },
  { id: 112, title: "Two Sum - LeetCode", url: "http://google.ca", favIconUrl: "https://leetcode.com/favicon-32x32.png" },
  { id: 113, title: "regex101:Regex Quiz", url: "http://google.ca", favIconUrl: "https://regex101.com/static/assets/favicon-32x32.png" },
  {
    id: 114,
    title: "60 JavaScript Interview Questions",
    url: "http://google.ca",
    favIconUrl: "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242173172/AOX1gE2jc.png",
  },

  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 26,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "数组-概览 | awesome-coding-js",
    url: "http://www.conardli.top/docs/dataStructure/%E6%95%B0%E7%BB%84/%E6%95%B0%E7%BB%84.html",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 27,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "和为S的连续正整数序列 | awesome-coding-js",
    url:
      "http://www.conardli.top/docs/dataStructure/%E6%95%B0%E7%BB%84/%E5%92%8C%E4%B8%BAS%E7%9A%84%E8%BF%9E%E7%BB%AD%E6%AD%A3%E6%95%B4%E6%95%B0%E5%BA%8F%E5%88%97.html#%E6%80%9D%E8%B7%AF",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://static.zhihu.com/heifetz/favicon.ico",
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 30,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "剑指 offer -- JavaScript 版 - 知乎",
    url: "https://zhuanlan.zhihu.com/p/31938189",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "http://madebyevan.com/favicon.ico",
    groupId: -1,
    height: 984,
    highlighted: false,
    id: 20,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "Continuous Calendar",
    url: "http://madebyevan.com/calendar/app/",
    width: 1792,
    windowId: 18,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://b-gold-cdn.xitu.io/favicons/v2/favicon.ico",
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 25,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "前端该如何准备数据结构和算法？",
    url: "https://juejin.cn/post/6844903919722692621",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://common.cnblogs.com/favicon.svg",
    groupId: -1,
    height: 983,
    highlighted: false,
    id: 32,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "剑指offer（4）重建二叉树 - 汕大小吴 - 博客园",
    url: "https://www.cnblogs.com/wuguanglin/p/reConstructBinaryTree.html",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    groupId: -1,
    height: 983,
    highlighted: false,
    id: 28,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "算法专题 | awesome-coding-js",
    url: "http://www.conardli.top/docs/algorithm/#%E6%8E%92%E5%BA%8F",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://codesandbox.io/favicon.ico",
    groupId: -1,
    height: 984,
    highlighted: false,
    id: 787,
    incognito: false,
    index: 2,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "Inline Text Edit React Hooks - CodeSandbox",
    url: "https://codesandbox.io/s/inline-text-edit-react-hooks-6ql5m?from-embed=&file=/src/components/inlineEdit.js:534-540",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://shenlvmeng.github.io/blog/favicon.png?v=5.1.1",
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 29,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "《剑指Offer》JavaScript版解决方案 | Shenlvmeng's Blog",
    url: "https://shenlvmeng.github.io/blog/2017/07/27/interview-algorithm-md/",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://common.cnblogs.com/favicon.svg",
    groupId: -1,
    height: 1015,
    highlighted: false,
    id: 31,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "unloaded",
    title: "JS版剑指offer - 汕大小吴 - 博客园",
    url: "https://www.cnblogs.com/wuguanglin/p/code-interview.html",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://miro.medium.com/fit/c/256/256/1*iETPsI-y6GMmx-AJEQRBnw@2x.png",
    groupId: -1,
    height: 984,
    highlighted: false,
    id: 571,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "You Must Understand These 14 JavaScript Functions | by bytefish | JavaScript in Plain English",
    url: "https://javascript.plainenglish.io/you-must-understand-these-14-javasript-functions-1f4fa1c620e2",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://joelmturner.com/favicon-32x32.png?v=ef8f8fe673e39fc3ef71b1a2f3894509",
    groupId: -1,
    height: 984,
    highlighted: false,
    id: 762,
    incognito: false,
    index: 1,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "Build an Inline Edit Text Input With React Hooks | Joel M. Turner",
    url: "https://joelmturner.com/blog/inline-text-edit-react-hooks/",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://www.youtube.com/s/desktop/c85ce30b/img/favicon_32.png",
    groupId: -1,
    height: 983,
    highlighted: false,
    id: 278,
    incognito: false,
    index: 10,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "js 算法 - YouTube",
    url: "https://www.youtube.com/results?search_query=js+%E7%AE%97%E6%B3%95",
    width: 1792,
    windowId: 24,
  },
  {
    active: false,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242173172/AOX1gE2jc.png",
    groupId: -1,
    height: 984,
    highlighted: false,
    id: 578,
    incognito: false,
    index: 0,
    mutedInfo: {
      muted: false,
    },
    pinned: false,
    selected: false,
    status: "complete",
    title: "60 JavaScript Interview Questions",
    url: "https://hemant.hashnode.dev/60-javascript-interview-questions",
    width: 1792,
    windowId: 24,
  },
];

export default initalData;
